# **Section 4: Data Containter**
+ List
+ String
+ Tuple
+ Dictionary
+ Set

## **List**
+ is a collection which is ordered, in-place and changeable. Allows duplicate members.

#### **declaring a list**

In [ ]:
# define a list with []
a = []
print(a)
print(type(a))

In [ ]:
# list with initial elements
a = [1, 2, 3, "amir", -2+5j, 3.14]
print(a)
# get tge length of the list
print("len: ", len(a))

In [ ]:
# list within list
a = [1, 2, ["amir", "reza"], 3.001]
print(a)
print("len: ", len(a))

In [ ]:
# declare with constructor
a = list("amir")
print(a)

In [ ]:
# this is a pitfall
a = list([3, 2, 6, "aa", "bb", 7])
print(a)

In [ ]:
# list generated by range()

a = range(10)
print(a, type(a))

<center><img src="res/wtf.jpg" width="300"/></center>

In [ ]:
# lest try something cool
a = list(range(10))
print(a, type(a))

In [ ]:
a = list(range(10, 100, 5))
print(a)
print("len:", len(a))

### **indexing and slicing**

In [ ]:
# simple indexing 
a = list("Amir Reza Ghorbani")
print(a[0])
print(a[6])

In [ ]:
# negative indexing
print(a[-1])
print(a[-8])

In [ ]:
# slicing
x = a[0:2]
print("x: ", x)
y = a[:]
print("y: ", y)
z = a[:5]
print("z: ", z)
w = a[5:]
print("w: ", w)

In [ ]:
# negative slicing
x = a[-9:-2]
print("x: ", x)

A step can also be used after a second colon to, say, take every other element:

In [ ]:
# stepping with slicing
x = a[ : : 2]
print("x: ", x)
y = a[0 : 10 : 5]
print("y: ", y)
z = a [ : : -2]
print("z: ", z)
w = a [ : : -1]
print("w: ", w)

### **assigning and altering the lists**

In [ ]:
a = list("Amir Reza Ghorbani")
a[10:] = "Loves Python"
print(a)

In [ ]:
# this one is wierd !!!
a = list(range(10))
a[-1:] = [-999, -888, -777]
print("1 => ", a)

# list concatination 
print("2 => ", a + ["i ", "am ", "a ", "new ", "list"])

### **[list functions](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists)**

In [ ]:
a = [1, 2, 3, 4, 5]
print("1 => ", a)

a.append(2)
print("2 => ", a)

a.extend([3, 3, 3, 3, 5])
print("3 => ", a)

print("4 => ", a.count(3))

a.reverse()
print("5 => ", a)

exist = 9 in a
print("6 => ", exist)

### **Simple example**

In [ ]:
a = list(range(10))
a.reverse()
b =[]

for element in a:
    b.append(element ** 2)

print("a : ", a)
print("b : ", b)

In [ ]:
# we use a built-in function called zip() to pair these two lists
c = zip(a, b)
print("c : ", c)
print(type(c))
print(list(c))

## **tuple**
<center><img src="res/tuplevslist.png" width=""/></center>

In [ ]:
# A tuple is a fixed-length, immutable sequence of Python objects.The easiest way to
# create one is with a comma-separated sequence of values:
tup = 4,5,6
print(tup, "    TYPE: ", type(tup) )

In [ ]:
#When you’re defining tuples in more complicated expressions, it’s often necessary to
#enclose the values in parentheses, as in this example of creating a tuple of tuples:
nested_tup = (4, 5, 6), (7, 8)
print(nested_tup)

In [ ]:
# You can convert any sequence or iterator to a tuple by invoking tuple 
a = tuple("Amir Reza")
b = tuple([1, 2, 3, 5])
print("a : ", a)
print("b : ", b)

In [ ]:
# tuples can not change their elements !!
b[0] = 9

In [ ]:
# unpacking a tuple
a = (2, 3, "Amir")

x, y, z = a
print("x : ", x)
print("y : ", y)
print("z : ", z)

### **simple example**

In [ ]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
for a,b,c in seq:
    print("a : ", a)
    print("b : ", b)    
    print("c : ", c)
    
    print(" ****** ")

### <font color=red >**Note that all of the indexing and slicing for tuples are just like lists**</font>

### **Strings**

In [ ]:
a = "Amir Reza" # or 'Amir reza'
print(len(a))

In [ ]:
print(a[2])

In [ ]:
# strings are immutable
a[0] = "a"

### [**String Functions**](https://www.programiz.com/python-programming/methods/string)

### **String Templating**

+ using `format()`
+ using python F String

In [ ]:
# using .format()
name = input("Enter Your Name: ")
age = input("Enter Your Age: ")

m = "My Name is {} and I am {} y.o".format(name, age)
print(m)

In [87]:
# using F String 
name = input("Enter Your Name: ")
age = input("Enter Your Age: ")

m = F"My Name is {name} and I am {age} y.o"
print(m)

Enter Your Name:  adsad
Enter Your Age:  22

My Name is adsad  and I am 22 y.o

### [**Special Characters**](https://www.quackit.com/python/reference/python_3_escape_sequences.cfm)
+ \t : tab or 4 spaces
+ \n : newline
+ ...

In [90]:
print("Amir\tReza")

Amir	Reza

In [92]:
print("22\n33\n44")

22
33
44

## **Dictionaries**
<center><img src="res/dict.png" width=""/></center>

In [94]:
a = {}
print("a: ", a)
print(type(a))

a:  {}
<class 'dict'>

In [114]:
a = {"name": "Amir", "age": 22}
print(a)
b = dict(city="fouman", state="guilan", a_list=[1, 2, 3])
print(b)

{'name': 'Amir', 'age': 22}
{'city': 'fouman', 'state': 'guilan', 'a_list': [1, 2, 3]}

In [102]:
print("Name : ", a["name"])
print("Age : ", a.get("age"))

Name :  Amir
Age :  22

In [107]:
# analyse and predict the output !!!
a = 1, 2, 3
b = "amir", "reza", "ghorbani"

c = zip(a, b)

d = dict(c)
d[4] = "Saravani"
print(d)

{1: 'amir', 2: 'reza', 3: 'ghorbani', 4: 'Saravani'}

In [115]:
print(d.keys())
print(d.values())
print(d.items())

dict_keys([1, 2, 3])
dict_values(['amir', 'reza', 'ghorbani'])
dict_items([(1, 'amir'), (2, 'reza'), (3, 'ghorbani')])

In [109]:
del d[4]
print(d)

{1: 'amir', 2: 'reza', 3: 'ghorbani'}

In [112]:
# see if a key exist in the dict or not
print(1 in d)
print(4 in d)

True
False

<center><img src="res/dictfunctions.png" width=""/></center>

## **Sets**

A set is a collection which is **unordered** , **unindexed** and **immutable**. In Python sets are written with curly brackets

In [116]:
a = set()
print(a, "   TYPE: ", type(a))

set()    TYPE:  <class 'set'>

In [117]:
# repetitive elements will get deleted
a = {1, 2, 3, 4, 4, 3}
print(a)

{1, 2, 3, 4}

In [118]:
for elem in a:
    print(elem)

1
2
3
4

In [120]:
a = set("amir reza ghorbani")
print(a)

{'i', 'o', 'm', 'b', 'a', 'n', 'h', 'r', 'z', ' ', 'g', 'e'}

In [121]:
print("z" in a)

True

<center><img src="res/set.webp" width="500"/></center>

### [**Sets Functions**](https://snakify.org/en/lessons/sets/)

<center><img src="res/setops.png" width=""/></center>

In [124]:
# example
A = {1, 2, 3, 4}
B = {3, 4, 5, 6}

print("Union: ", A.union(B))
print("Intersction: ", A.intersection(B))
print("Difference: ", A.difference(B))

Union:  {1, 2, 3, 4, 5, 6}
Intersction:  {3, 4}
Difference:  {1, 2}